### ISSUE TITLE
script:progressbar:warning:entity Warning: GetNetworkObject: no object by ID 0

### ISSUE THREAD

**Issue by ProCoderLabs** [qbcore-framework/progressbar#18] opened 2022-12-08 23:42 UTC
fresh install of latest qbcore, when i combine anything i get a warning saying

script:progressbar:warning:entity Warning: GetNetworkObject: no object by ID 0

nothing extra added brand new install. any ideas

**Comment by Z3rio** [comment] 2022-12-09 00:01
Hello, could you please show a screenshot of the error. 
And also include steps to recreate this // what you did to make this happen.

**Comment by ProCoderLabs** [comment] 2022-12-09 00:47
[https://cdn.discordapp.com/attachments/1050087527580696600/1050574277319069736/Capture.PNG](url)

fresh install, go to combine an item
 thats all

**Comment by ProCoderLabs** [comment] 2022-12-09 00:49
[https://cdn.discordapp.com/attachments/1050087527580696600/1050574653988556920/image.png](url)

also fresh install nothing else and getting the error underneath aswell

and the error with the screenshot, i did a fresh server last week and it was fine. did one today and just getting errors, i built quite a few servers and this is new to me from a fresh install

**Comment by ProCoderLabs** [comment] 2022-12-09 00:52
[     38282] [b2699_GTAProce]             MainThrd/ ^2[AUTH] logged in as 'MD.GamesMaster' with perms: ["all_permissions"]
[     38282] [b2699_GTAProce]             MainThrd/ ^2ServerCtx updated from global state
[     38532] [b2699_GTAProce]             MainThrd/ Returning device Headset Earphone (CORSAIR VOID ELITE Wireless Gaming Dongle) for GUID {3AED98B8-9AD8-4977-BF1E-C697AFF2D098}
[     38594] [b2699_GTAProce] [Mumble] Audio Input/ Returning device Headset Microphone (CORSAIR VOID ELITE Wireless Gaming Dongle) for GUID {D9BBFCB0-379F-459D-9B63-3F01BE2C1EA1}
[     38594] [b2699_GTAProce] [Mumble] Audio Input/ MumbleAudioInput::InitializeAudioDevice: Initialized audio capture device.
[     38719] [b2699_GTAProce]             MainThrd/ Connecting to mumble, setting targets.
[     38891] [b2699_GTAProce]        CrBrowserMain/ THREE.WebGLRenderer 101dev (@screenshot-basic/dist/ui.html:15)
[     38938] [b2699_GTAProce]             MainThrd/ Script initialization finished.
[     38969] [b2699_GTAProce]        CrBrowserMain/ f? (@screenshot-basic/dist/ui.html:15)
[     39250] [b2699_GTAProce]             MainThrd/ Finished connection logic
[     39328] [b2699_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read properties of null (reading 'focus') (@game/ui/root.html:108)
[     39344] [b2699_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read properties of null (reading 'focus') (@game/ui/root.html:108)
[     72063] [b2699_GTAProce]             MainThrd/ ^3Warning: GetNetworkObject: no object by ID 0^7
[     72063] [b2699_GTAProce]             MainThrd/ ^3Warning: GetNetworkObject: no object by ID 0^7
[     72063] [b2699_GTAProce]             MainThrd/ ^3Warning: GetNetworkObject: no object by ID 0^7
[     72063] [b2699_GTAProce]             MainThrd/ ^3Warning: GetNetworkObject: no object by ID 0^7
[    109313] [b2699_GTAProce]             MainThrd/ 
[    167735] [b2699_GTAProce]             MainThrd/ 
[    168594] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset v_hospital.ybn.
[    168594] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    168594] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 64879, when there are only 2880 vertices.
[    596922] [b2699_GTAProce]        CrBrowserMain/ Uncaught (in promise) Error: Style of type: info, does not exist in the config (@qb-core/html/js/config.js:28)
[    945375] [b2699_GTAProce]                24168/ ResourceCache::AddEntry: Saved cache:v1:bbe3406af4f06bfd18ea4f50c6549c621787af43 to the index cache.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 65520, when there are only 120 vertices.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 44 edge reference is invalid. It leads to vertex 65326, when there are only 6922 vertices.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 10 edge reference is invalid. It leads to vertex 60, when there are only 56 vertices.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 29 edge reference is invalid. It leads to vertex 2427, when there are only 2412 vertices.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 53 edge reference is invalid. It leads to vertex 3855, when there are only 3808 vertices.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 19 edge reference is invalid. It leads to vertex 65128, when there are only 2212 vertices.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Physics validation failed for asset hei_bh1_04_0.ybn.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ This asset is **INVALID**, but we've fixed it for this load. Please fix the exporter used to export it.
[    947766] [b2699_GTAProce] ResourcePlacementThr/ Details: Poly 0 edge reference is invalid. It leads to vertex 63178, when there are only 2563 vertices.

**Comment by ProCoderLabs** [comment] 2022-12-09 00:55
just looking through discord jimathy is having an issue just like it

[https://cdn.discordapp.com/attachments/921127442582732820/1050508997066756167/image.png](url)

**Comment by jnccloud** [comment] 2022-12-09 04:22
If you guys want to test my PR, it should fix your issues. 

https://github.com/qbcore-framework/progressbar/pull/19

**Comment by ProCoderLabs** [comment] 2022-12-09 15:06
erm no even more broken. no progress bar and no item given after combine. also cant open inventory after

[     41984] [b2699_GTAProce]             MainThrd/ ^2[AUTH] logged in as 'MD.GamesMaster' with perms: ["all_permissions"]
[     41984] [b2699_GTAProce]             MainThrd/ React loaded, sending variables.
[     41984] [b2699_GTAProce]             MainThrd/ ^2ServerCtx updated from global state
[     42203] [b2699_GTAProce]             MainThrd/ Returning device Headset Earphone (CORSAIR VOID ELITE Wireless Gaming Dongle) for GUID {3AED98B8-9AD8-4977-BF1E-C697AFF2D098}
[     42265] [b2699_GTAProce] [Mumble] Audio Input/ Returning device Headset Microphone (CORSAIR VOID ELITE Wireless Gaming Dongle) for GUID {D9BBFCB0-379F-459D-9B63-3F01BE2C1EA1}
[     42281] [b2699_GTAProce] [Mumble] Audio Input/ MumbleAudioInput::InitializeAudioDevice: Initialized audio capture device.
[     42406] [b2699_GTAProce]             MainThrd/ Connecting to mumble, setting targets.
[     42640] [b2699_GTAProce]        CrBrowserMain/ THREE.WebGLRenderer 101dev (@screenshot-basic/dist/ui.html:15)
[     42656] [b2699_GTAProce]             MainThrd/ Script initialization finished.
[     42734] [b2699_GTAProce]        CrBrowserMain/ f? (@screenshot-basic/dist/ui.html:15)
[     42922] [b2699_GTAProce]             MainThrd/ Finished connection logic
[     43109] [b2699_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read properties of null (reading 'focus') (@game/ui/root.html:108)
doesnt seem to be kicking much in errors tho

**Comment by FrequencyRoleplay** [comment] 2022-12-09 20:57
updated earlier and it was broken but just updated again and seems to be working well. GOOD JOB!!! and thanks!

Also...
what was the issue causing the no network ID.?
I have another script doing the same but the dev cant track it down

**Comment by jnccloud** [comment] 2022-12-10 10:22
> updated earlier and it was broken but just updated again and seems to be working well. GOOD JOB!!! and thanks!
> 
> Also... what was the issue causing the no network ID.? I have another script doing the same but the dev cant track it down

Are you using the PR I put in (it wasn't merged) or are you running the latest updates to progressbar?

And to my understanding, it's caused by trying to access an entity that doesn't exist yet. So you need to make sure it exists before asking the game to do something to it. So any natives that have the word "Net" or "Network" in them can be a culprit. Like NetToObj() or ObjToNet() or StartNetworkedParticleFxNonLoopedAtCoord().. calls like that. You want to be sure the object exists before trying to access it; so DoesEntityExist(object) helps prevent the warning.

And these are purely warnings until CFX says otherwise. They have ALWAYS printed out, but just recently the logs show the script that is causing them, so they're actually fixable now.

**Closed as completed** 2022-12-14 16:59 UTC
